"""
Django settings for pgschemas_async project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import dj_database_url
from getenv import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--@ry4ur%8o$kittt-w$@q02wp1%a)=^t4b$@_*kb1$42tbsbqd"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
TENANT_APPS = ["tenant_example"]

# Application definition

SHARED_APPS = [
    "django_pgschemas",
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "clients",
    "client_users",
    "pgschemas_async",
]


INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]


TENANTS = {
    "public": {"APPS": SHARED_APPS},
    # ...
    "default": {
        "TENANT_MODEL": "clients.Client",
        "DOMAIN_MODEL": "clients.Domain",
        "APPS": TENANT_APPS,
        "URLCONF": "pgschemas_async.urls",
        "WS_URLCONF": "pgschemas_async.ws_urls",
    },
}

ROOT_URLCONF = TENANTS["default"]["URLCONF"]

MIDDLEWARE = [
    "django_pgschemas.middleware.TenantMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "pgschemas_async.wsgi.application"
ASGI_APPLICATION = "pgschemas_async.asgi.application"

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
db_from_env = env("DATABASE_CONNECTION_STRING", None)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

### Import from URL to start
DATABASES["default"] = dj_database_url.config(default=db_from_env)
### Then replace the engine
DATABASES["default"]["ENGINE"] = "django_pgschemas.postgresql_backend"
DATABASES["default"]["DATABASE"] = "default"

DATABASE_ROUTERS = [
    "django_pgschemas.routers.SyncRouter",
]

AUTH_USER_MODEL = "client_users.ClientUser"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = "/home/docker/volatile/static"
MEDIA_ROOT = "/home/docker/persistent/media"

SESSION_COOKIE_DOMAIN = ".zd-local.com"
SESSION_COOKIE_NAME = "pgasync_sessionid"
