version: '3.7'
volumes:
  postgresdata:

services:
  db:
    image: postgres:13
    ports:
      - "15432:5432"
    container_name: pgschemas_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password

  app:
    image: test_app
    container_name: pgschemas_app
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:8000"
    volumes:
      - ./pgschemas_async:/home/docker/code/app
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://postgres:password@pgschemas_db/postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
    command: bash -c "make dev"



