# Generated by Django 4.1.3 on 2022-11-07 16:16

from django.db import migrations, models
import django.db.models.deletion
import django_pgschemas.schema
import django_pgschemas.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[django_pgschemas.utils.check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(django_pgschemas.schema.SchemaDescriptor, models.Model),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('folder', models.SlugField(blank=True, max_length=253)),
                ('is_primary', models.BooleanField(default=True)),
                ('redirect_to_primary', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='clients.client')),
            ],
            options={
                'ordering': ['tenant', 'domain'],
            },
        ),
    ]
